import UIKit

enum DAForm705PDFService {

    static func generatePDF(from data: DAForm705ExportData) -> Data? {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let margin: CGFloat = 36
        let contentWidth = pageWidth - margin * 2

        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { context in
            context.beginPage()

            var y: CGFloat = margin

            y = drawHeader(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, pageWidth: pageWidth)
            y = drawUnofficialBanner(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth)
            y = drawSoldierInfo(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, data: data)
            y = drawTestInfo(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, data: data)
            y = drawEventScores(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, data: data)
            y = drawTotalAndResult(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, data: data)

            drawFooter(in: context.cgContext, margin: margin, pageWidth: pageWidth, pageHeight: pageHeight)
        }
    }

    static func savePDFToTemp(data: Data, soldierName: String) -> URL? {
        let sanitized = soldierName.isEmpty ? "Soldier" : soldierName.replacingOccurrences(of: " ", with: "_")
        let dateStr = DateFormatter.shortFileDate.string(from: .now)
        let fileName = "AFT_Score_Report_\(sanitized)_\(dateStr).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        do {
            try data.write(to: url)
            return url
        } catch {
            return nil
        }
    }

    // MARK: - Drawing Sections

    private static func drawHeader(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        var currentY = y

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 14),
            .foregroundColor: UIColor.black
        ]
        let subtitleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.darkGray
        ]

        let title = "AFT SCORE REPORT — UNOFFICIAL"
        let titleSize = (title as NSString).size(withAttributes: titleAttrs)
        let titleX = (pageWidth - titleSize.width) / 2
        (title as NSString).draw(at: CGPoint(x: titleX, y: currentY), withAttributes: titleAttrs)
        currentY += titleSize.height + 2

        let formId = "Generated by GetFit"
        let formSize = (formId as NSString).size(withAttributes: subtitleAttrs)
        let formX = (pageWidth - formSize.width) / 2
        (formId as NSString).draw(at: CGPoint(x: formX, y: currentY), withAttributes: subtitleAttrs)
        currentY += formSize.height + 12

        return currentY
    }

    private static func drawUnofficialBanner(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat) -> CGFloat {
        var currentY = y

        let bannerRect = CGRect(x: margin, y: currentY, width: contentWidth, height: 22)
        ctx.setFillColor(UIColor(red: 0.95, green: 0.90, blue: 0.75, alpha: 1.0).cgColor)
        ctx.fill(bannerRect)
        ctx.setStrokeColor(UIColor(red: 0.75, green: 0.60, blue: 0.30, alpha: 1.0).cgColor)
        ctx.setLineWidth(0.5)
        ctx.stroke(bannerRect)

        let bannerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 8),
            .foregroundColor: UIColor(red: 0.5, green: 0.3, blue: 0.0, alpha: 1.0)
        ]
        let bannerText = "UNOFFICIAL — FOR PERSONAL REFERENCE ONLY — NOT AN OFFICIAL ARMY RECORD"
        let bannerSize = (bannerText as NSString).size(withAttributes: bannerAttrs)
        let bannerX = margin + (contentWidth - bannerSize.width) / 2
        (bannerText as NSString).draw(at: CGPoint(x: bannerX, y: currentY + 6), withAttributes: bannerAttrs)
        currentY += 22 + 12

        return currentY
    }

    private static func drawSoldierInfo(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        var currentY = y

        currentY = drawSectionHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, title: "I. SOLDIER INFORMATION")

        let halfWidth = (contentWidth - 8) / 2
        let thirdWidth = (contentWidth - 16) / 3

        currentY = drawLabeledField(in: ctx, at: currentY, x: margin, width: contentWidth, label: "1. NAME", value: data.soldierName)

        let row3Y = currentY
        drawLabeledField(in: ctx, at: row3Y, x: margin, width: thirdWidth, label: "2. AGE", value: "\(data.age)")
        drawLabeledField(in: ctx, at: row3Y, x: margin + thirdWidth + 8, width: thirdWidth, label: "3. SEX", value: data.sex.rawValue)
        currentY = drawLabeledField(in: ctx, at: row3Y, x: margin + (thirdWidth + 8) * 2, width: thirdWidth, label: "4. STANDARD", value: data.standard.rawValue)

        currentY += 6
        return currentY
    }

    private static func drawTestInfo(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        var currentY = y

        currentY = drawSectionHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, title: "II. TEST INFORMATION")

        let halfWidth = (contentWidth - 8) / 2
        let row1Y = currentY
        drawLabeledField(in: ctx, at: row1Y, x: margin, width: halfWidth, label: "5. TYPE", value: "Example Score")
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "dd MMM yyyy"
        currentY = drawLabeledField(in: ctx, at: row1Y, x: margin + halfWidth + 8, width: halfWidth, label: "6. DATE", value: dateFormatter.string(from: data.testDate))

        currentY += 6
        return currentY
    }

    private static func drawEventScores(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        var currentY = y

        currentY = drawSectionHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, title: "III. EVENT SCORES")

        let colWidths: [CGFloat] = [30, contentWidth * 0.30, contentWidth * 0.28, contentWidth * 0.15]
        let pointsWidth = contentWidth - colWidths[0] - colWidths[1] - colWidths[2] - colWidths[3]

        currentY = drawEventTableHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, colWidths: colWidths, pointsWidth: pointsWidth)

        let events: [(String, String, String, Int)] = [
            ("1", "3 REPETITION MAXIMUM DEADLIFT (MDL)", "\(data.deadliftLbs) lbs", data.deadliftPoints),
            ("2", "HAND RELEASE PUSH-UP (HRP)", "\(data.pushUpReps) reps", data.pushUpPoints),
            ("3", "SPRINT-DRAG-CARRY (SDC)", formatTime(data.sdcSeconds), data.sdcPoints),
            ("4", "PLANK (PLK)", formatTime(data.plankSeconds), data.plankPoints),
            ("5", "TWO-MILE RUN (2MR)", formatTime(data.runSeconds), data.runPoints)
        ]

        for (num, name, raw, points) in events {
            currentY = drawEventRow(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, colWidths: colWidths, pointsWidth: pointsWidth, num: num, name: name, raw: raw, points: points, minPoints: data.standard.minimumPerEvent)
        }

        currentY += 6
        return currentY
    }

    private static func drawEventTableHeader(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, colWidths: [CGFloat], pointsWidth: CGFloat) -> CGFloat {
        let rowHeight: CGFloat = 20
        let headerRect = CGRect(x: margin, y: y, width: contentWidth, height: rowHeight)
        ctx.setFillColor(UIColor(white: 0.90, alpha: 1).cgColor)
        ctx.fill(headerRect)
        ctx.setStrokeColor(UIColor.black.cgColor)
        ctx.setLineWidth(0.5)
        ctx.stroke(headerRect)

        let headerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 7),
            .foregroundColor: UIColor.black
        ]

        let headers = ["#", "EVENT", "RAW SCORE", "SCALED", "POINTS"]
        var x = margin + 4
        for (i, header) in headers.enumerated() {
            let w = i < colWidths.count ? colWidths[i] : pointsWidth
            (header as NSString).draw(at: CGPoint(x: x, y: y + 5), withAttributes: headerAttrs)
            x += w
        }

        return y + rowHeight
    }

    private static func drawEventRow(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, colWidths: [CGFloat], pointsWidth: CGFloat, num: String, name: String, raw: String, points: Int, minPoints: Int) -> CGFloat {
        let rowHeight: CGFloat = 24
        let rowRect = CGRect(x: margin, y: y, width: contentWidth, height: rowHeight)
        ctx.setStrokeColor(UIColor(white: 0.75, alpha: 1).cgColor)
        ctx.setLineWidth(0.3)
        ctx.stroke(rowRect)

        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.black
        ]
        let pointsAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 10),
            .foregroundColor: points >= minPoints ? UIColor(red: 0, green: 0.5, blue: 0, alpha: 1) : UIColor.red
        ]

        let passStr = points >= minPoints ? "GO" : "NO GO"
        let passAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 8),
            .foregroundColor: points >= minPoints ? UIColor(red: 0, green: 0.5, blue: 0, alpha: 1) : UIColor.red
        ]

        var x = margin + 4
        let textY = y + 7

        (num as NSString).draw(at: CGPoint(x: x, y: textY), withAttributes: valueAttrs)
        x += colWidths[0]

        (name as NSString).draw(at: CGPoint(x: x, y: textY), withAttributes: [.font: UIFont.systemFont(ofSize: 8), .foregroundColor: UIColor.black])
        x += colWidths[1]

        (raw as NSString).draw(at: CGPoint(x: x, y: textY), withAttributes: valueAttrs)
        x += colWidths[2]

        (passStr as NSString).draw(at: CGPoint(x: x, y: textY), withAttributes: passAttrs)
        x += colWidths[3]

        ("\(points)" as NSString).draw(at: CGPoint(x: x, y: textY - 1), withAttributes: pointsAttrs)

        return y + rowHeight
    }

    private static func drawTotalAndResult(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        var currentY = y

        let totalRect = CGRect(x: margin, y: currentY, width: contentWidth, height: 32)
        ctx.setFillColor(UIColor(white: 0.93, alpha: 1).cgColor)
        ctx.fill(totalRect)
        ctx.setStrokeColor(UIColor.black.cgColor)
        ctx.setLineWidth(0.5)
        ctx.stroke(totalRect)

        let totalLabelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 11),
            .foregroundColor: UIColor.black
        ]
        let totalValueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 14),
            .foregroundColor: UIColor.black
        ]
        let resultColor: UIColor = data.passed ? UIColor(red: 0, green: 0.5, blue: 0, alpha: 1) : .red
        let resultAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 12),
            .foregroundColor: resultColor
        ]

        ("TOTAL SCORE:" as NSString).draw(at: CGPoint(x: margin + 8, y: currentY + 8), withAttributes: totalLabelAttrs)
        ("\(data.totalScore) / 500" as NSString).draw(at: CGPoint(x: margin + 120, y: currentY + 7), withAttributes: totalValueAttrs)

        let resultStr = data.passed ? "PASS (GO)" : "FAIL (NO GO)"
        let resultSize = (resultStr as NSString).size(withAttributes: resultAttrs)
        (resultStr as NSString).draw(at: CGPoint(x: margin + contentWidth - resultSize.width - 12, y: currentY + 9), withAttributes: resultAttrs)

        currentY += 32 + 6

        let minAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 8),
            .foregroundColor: UIColor.darkGray
        ]
        let minText = "Standard: \(data.standard.rawValue) — Min \(data.standard.minimumPerEvent) pts/event, \(data.standard.minimumTotal) pts total"
        (minText as NSString).draw(at: CGPoint(x: margin, y: currentY), withAttributes: minAttrs)
        currentY += 16

        return currentY
    }

    private static func drawBodyComposition(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        let hasData = !data.height.isEmpty || !data.weight.isEmpty || !data.bodyFatPercent.isEmpty || !data.bodyCompDate.isEmpty
        guard hasData else { return y }

        var currentY = y
        currentY = drawSectionHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, title: "IV. BODY COMPOSITION")

        let quarterWidth = (contentWidth - 24) / 4
        let rowY = currentY
        drawLabeledField(in: ctx, at: rowY, x: margin, width: quarterWidth, label: "HEIGHT", value: data.height)
        drawLabeledField(in: ctx, at: rowY, x: margin + quarterWidth + 8, width: quarterWidth, label: "WEIGHT", value: data.weight)
        drawLabeledField(in: ctx, at: rowY, x: margin + (quarterWidth + 8) * 2, width: quarterWidth, label: "BODY FAT %", value: data.bodyFatPercent)
        currentY = drawLabeledField(in: ctx, at: rowY, x: margin + (quarterWidth + 8) * 3, width: quarterWidth, label: "BC DATE", value: data.bodyCompDate)

        currentY += 6
        return currentY
    }

    private static func drawAuthentication(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, data: DAForm705ExportData) -> CGFloat {
        var currentY = y

        currentY = drawSectionHeader(in: ctx, at: currentY, margin: margin, contentWidth: contentWidth, title: "V. AUTHENTICATION")

        let halfWidth = (contentWidth - 8) / 2
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "dd MMM yyyy"

        let row1Y = currentY
        drawLabeledField(in: ctx, at: row1Y, x: margin, width: halfWidth, label: "SOLDIER NAME", value: data.soldierName)
        currentY = drawLabeledField(in: ctx, at: row1Y, x: margin + halfWidth + 8, width: halfWidth, label: "DATE", value: dateFormatter.string(from: data.testDate))

        let hasOIC = !data.oicName.isEmpty || !data.oicDate.isEmpty
        let hasNCOIC = !data.ncoicName.isEmpty || !data.ncoicDate.isEmpty

        if hasOIC {
            let row2Y = currentY
            drawLabeledField(in: ctx, at: row2Y, x: margin, width: halfWidth, label: "OIC / NCOIC NAME", value: data.oicName)
            currentY = drawLabeledField(in: ctx, at: row2Y, x: margin + halfWidth + 8, width: halfWidth, label: "DATE", value: data.oicDate)
        }

        if hasNCOIC {
            let row3Y = currentY
            drawLabeledField(in: ctx, at: row3Y, x: margin, width: halfWidth, label: "NCOIC NAME", value: data.ncoicName)
            currentY = drawLabeledField(in: ctx, at: row3Y, x: margin + halfWidth + 8, width: halfWidth, label: "DATE", value: data.ncoicDate)
        }

        let sigLineY = currentY + 10
        ctx.setStrokeColor(UIColor.black.cgColor)
        ctx.setLineWidth(0.5)

        let sigLabelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 7),
            .foregroundColor: UIColor.darkGray
        ]

        ctx.move(to: CGPoint(x: margin, y: sigLineY + 14))
        ctx.addLine(to: CGPoint(x: margin + halfWidth, y: sigLineY + 14))
        ctx.strokePath()
        ("SOLDIER'S SIGNATURE" as NSString).draw(at: CGPoint(x: margin, y: sigLineY + 16), withAttributes: sigLabelAttrs)

        ctx.move(to: CGPoint(x: margin + halfWidth + 8, y: sigLineY + 14))
        ctx.addLine(to: CGPoint(x: margin + contentWidth, y: sigLineY + 14))
        ctx.strokePath()
        ("OIC / NCOIC SIGNATURE" as NSString).draw(at: CGPoint(x: margin + halfWidth + 8, y: sigLineY + 16), withAttributes: sigLabelAttrs)

        currentY = sigLineY + 32
        return currentY
    }

    private static func drawFooter(in ctx: CGContext, margin: CGFloat, pageWidth: CGFloat, pageHeight: CGFloat) {
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 7),
            .foregroundColor: UIColor.gray
        ]
        let footerY = pageHeight - margin + 4
        let dateStr = DateFormatter.shortFileDate.string(from: .now)

        let leftText = "AFT SCORE REPORT — UNOFFICIAL"
        (leftText as NSString).draw(at: CGPoint(x: margin, y: footerY), withAttributes: footerAttrs)

        let rightText = "Generated \(dateStr) — GetFit App"
        let rightSize = (rightText as NSString).size(withAttributes: footerAttrs)
        (rightText as NSString).draw(at: CGPoint(x: pageWidth - margin - rightSize.width, y: footerY), withAttributes: footerAttrs)
    }

    // MARK: - Primitive Helpers

    @discardableResult
    private static func drawSectionHeader(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, title: String) -> CGFloat {
        let headerRect = CGRect(x: margin, y: y, width: contentWidth, height: 20)
        ctx.setFillColor(UIColor(white: 0.15, alpha: 1).cgColor)
        ctx.fill(headerRect)

        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 9),
            .foregroundColor: UIColor.white
        ]
        (title as NSString).draw(at: CGPoint(x: margin + 8, y: y + 5), withAttributes: attrs)

        return y + 20 + 4
    }

    @discardableResult
    private static func drawLabeledField(in ctx: CGContext, at y: CGFloat, x: CGFloat, width: CGFloat, label: String, value: String) -> CGFloat {
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 7),
            .foregroundColor: UIColor.darkGray
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.black
        ]

        let fieldHeight: CGFloat = 30
        let fieldRect = CGRect(x: x, y: y, width: width, height: fieldHeight)
        ctx.setStrokeColor(UIColor(white: 0.75, alpha: 1).cgColor)
        ctx.setLineWidth(0.3)
        ctx.stroke(fieldRect)

        (label as NSString).draw(at: CGPoint(x: x + 4, y: y + 2), withAttributes: labelAttrs)

        let displayValue = value.isEmpty ? "—" : value
        (displayValue as NSString).draw(at: CGPoint(x: x + 4, y: y + 14), withAttributes: valueAttrs)

        return y + fieldHeight
    }

    private static func formatTime(_ totalSeconds: Int) -> String {
        let minutes = totalSeconds / 60
        let seconds = totalSeconds % 60
        return String(format: "%d:%02d", minutes, seconds)
    }
}

private extension DateFormatter {
    static let shortFileDate: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd"
        return f
    }()
}
