import Foundation

enum ExerciseLibrary {

    static let allExercises: [String] = [
        "400m Run",
        "800m Run",
        "Air Squat",
        "Alternating Dumbbell Bench Press",
        "Arnold Press",
        "Back Extensions",
        "Back Squat",
        "Barbell Back Squat",
        "Barbell Bench Press",
        "Barbell Bent-Over Row",
        "Barbell Complex",
        "Barbell Curl",
        "Barbell Deadlift",
        "Barbell Front Squat",
        "Barbell Hip Thrust",
        "Barbell Overhead Press",
        "Barbell Push Press",
        "Barbell Row",
        "Barbell Split Squat",
        "Bear Crawl",
        "Bench Press",
        "Bird Dog",
        "Box Jump",
        "Box Step-Up",
        "Broad Jump",
        "Bulgarian Split Squat",
        "Burpee",
        "Cable Chest Fly",
        "Cable Crossover",
        "Cable Fly",
        "Cable Lateral Raise",
        "Cable Pullover",
        "Cable Row",
        "Cable Triceps Extension",
        "Cable Upright Row",
        "Calf Raise",
        "Chest Supported Row",
        "Clean & Jerk",
        "Close-Grip Bench Press",
        "Close Grip Push-Up",
        "Concentration Curl",
        "Dead Bug",
        "Dead Hang",
        "Deadlift",
        "Deficit Deadlift",
        "Diamond Push-Up",
        "Dip",
        "Double-Unders",
        "Dumbbell Bench Press",
        "Dumbbell Clean and Press",
        "Dumbbell Curl",
        "Dumbbell Curl to Press",
        "Dumbbell Floor Press",
        "Dumbbell Fly",
        "Dumbbell Goblet Squat",
        "Dumbbell Incline Press",
        "Dumbbell Lateral Raise",
        "Dumbbell Lunges",
        "Dumbbell Overhead Press",
        "Dumbbell Press",
        "Dumbbell Push Press",
        "Dumbbell Renegade Row",
        "Dumbbell Reverse Fly",
        "Dumbbell Reverse Lunge",
        "Dumbbell Romanian Deadlift",
        "Dumbbell Row",
        "Dumbbell Shoulder Press",
        "Dumbbell Single-Arm Row",
        "Dumbbell Skull Crusher",
        "Dumbbell Snatch",
        "Dumbbell Squat Clean",
        "Dumbbell Step-Up",
        "Dumbbell Thruster",
        "EZ Bar Curl",
        "EZ Bar Skull Crusher",
        "Face Pull",
        "Farmer Carry",
        "Farmer's Walk",
        "Flat Barbell Bench Press",
        "Flat Dumbbell Bench Press",
        "Flat Dumbbell Fly",
        "Flutter Kicks",
        "Forearm Plank",
        "Front Rack Carry",
        "Front Squat",
        "Glute Bridge",
        "Glute Ham Raise",
        "Goblet Squat",
        "Good Morning",
        "Hack Squat",
        "Hammer Curl",
        "Hand-Release Push-Up",
        "Handstand Push-Up",
        "Hang Clean Pull",
        "Hang Power Clean",
        "Hanging Knee Raise",
        "Hanging Leg Raise",
        "Hex Bar Deadlift",
        "High Knee Sprint",
        "Hip Adductor",
        "Hip Bridge",
        "Hip Thrust",
        "Hollow Hold",
        "Incline Barbell Bench Press",
        "Incline Barbell Press",
        "Incline Bench Press",
        "Incline Curl",
        "Incline Dumbbell Bench Press",
        "Incline Dumbbell Curl",
        "Incline Dumbbell Fly",
        "Incline Dumbbell Press",
        "Incline Fly",
        "Jump Lunge",
        "Jump Squat",
        "Jumping Jack",
        "Jumping Lunge",
        "Kettlebell Clean & Jerk",
        "Kettlebell Clean & Press",
        "Kettlebell Farmer's Carry",
        "Kettlebell Goblet Squat",
        "Kettlebell Row",
        "Kettlebell Swing",
        "Kettlebell Turkish Get-Up",
        "Knees-to-Elbows",
        "Lat Pulldown",
        "Lateral Raise",
        "Lateral Shuffle",
        "Leg Curl",
        "Leg Extension",
        "Leg Press",
        "Lunges",
        "Meadows Row",
        "Medicine Ball Chest Pass",
        "Medicine Ball Slam",
        "Mountain Climber",
        "Muscle-Up",
        "Nordic Hamstring Curl",
        "Overhead Dumbbell Extension",
        "Overhead Press",
        "Overhead Squat",
        "Overhead Tricep Extension",
        "Paused Back Squat",
        "Pendlay Row",
        "Pistol Squat",
        "Plank",
        "Plank Drag",
        "Plank Jack",
        "Plank Shoulder Tap",
        "Plank Up-Down",
        "Plate Front Raise",
        "Power Clean",
        "Power Snatch",
        "Preacher Curl",
        "Pull-Up",
        "Push Jerk",
        "Push Press",
        "Push-Up",
        "Rear Delt Fly",
        "Rear Foot Elevated Split Squat",
        "Renegade Row",
        "Reverse Curl",
        "Reverse Lunge",
        "Ring Dip",
        "Romanian Deadlift",
        "Rope Climb",
        "Rope Triceps Pressdown",
        "Row",
        "Run",
        "Russian Twist",
        "Sandbag Carry",
        "Sandbag Front Carry",
        "Seated Cable Row",
        "Seated Calf Raise",
        "Seated Dumbbell Curl",
        "Seated Dumbbell Press",
        "Seated Dumbbell Shoulder Press",
        "Shoulder Press",
        "Shoulder Taps",
        "Side Plank",
        "Single-Arm Dumbbell Row",
        "Single-Arm Lat Pulldown",
        "Single-Leg Romanian Deadlift",
        "Sissy Squat",
        "Sit-Up",
        "Skater Hop",
        "Skull Crushers",
        "Sled Drag",
        "Sled Push",
        "Split Squat",
        "Sprint",
        "Standing Calf Raise",
        "Step-Up",
        "Stiff-Leg Deadlift",
        "Straight-Arm Pulldown",
        "Suitcase Carry",
        "Sumo Deadlift",
        "T-Bar Row",
        "Thruster",
        "Trap Bar Deadlift",
        "Tricep Dip",
        "Tricep Pushdown",
        "Tricep Rope Pushdown",
        "Turkish Get-Up",
        "Walking Lunge",
        "Wall Ball",
        "Weighted Carry",
        "Weighted Chin-Up",
        "Weighted Dip",
        "Weighted Hip Bridge",
        "Weighted Hip Thrust",
        "Weighted Pull-Up",
        "Weighted Sit-Up",
        "Wrist Curl",
        "Wrist Roller",
        "Bend and Reach",
        "Rear Lunge",
        "High Jumper",
        "Rower",
        "Squat Bender",
        "Windmill",
        "Forward Lunge",
        "Prone Row",
        "Bent-Leg Body Twist",
        "Bent-Leg Raise",
        "Side Bridge",
        "Back Bridge",
        "Quadraplex",
        "Overhead Arm Pull",
        "Extend and Flex",
        "Thigh Stretch",
        "Single-Leg Over",
        "Tempo Run",
        "Easy Jog",
        "Cool Down Jog",
        "Ruck March",
        "Bike",
        "Stationary Bike",
        "Swimming",
        "Rowing Machine"
    ]

    static func search(_ query: String) -> [String] {
        guard !query.isEmpty else { return [] }
        let lowered = query.lowercased()
        return allExercises.filter { $0.localizedStandardContains(lowered) }
    }

    static let weightedExerciseKeywords: Set<String> = [
        "barbell", "dumbbell", "kettlebell", "bench press", "deadlift", "squat",
        "press", "curl", "row", "fly", "raise", "extension", "pushdown",
        "thruster", "snatch", "clean", "jerk", "weighted", "goblet",
        "skull crusher", "hip thrust", "leg press", "leg curl", "leg extension",
        "hack squat", "t-bar", "cable", "trap bar", "hex bar", "ez bar",
        "farmer", "carry", "suitcase", "front rack", "sandbag", "sled",
        "wall ball", "medicine ball", "plate", "wrist", "calf raise",
        "good morning", "romanian", "stiff-leg", "deficit", "sumo",
        "split squat", "bulgarian", "step-up", "lunge", "vest"
    ]

    static func isWeightedExercise(_ name: String) -> Bool {
        let lowered = name.lowercased()
        return weightedExerciseKeywords.contains { lowered.contains($0) }
    }
}
