import UIKit

enum PTPlanPDFService {

    static func generatePDF(from plan: WeeklyPlan, goal: PTGoal?) -> Data? {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let margin: CGFloat = 36
        let contentWidth = pageWidth - margin * 2

        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { context in
            context.beginPage()

            var y: CGFloat = margin

            y = drawHeader(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, pageWidth: pageWidth, plan: plan, goal: goal)
            y = drawPlanSummary(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, plan: plan, goal: goal)

            for (index, day) in plan.days.enumerated() {
                let estimatedHeight: CGFloat = day.isRestDay ? 40 : CGFloat(60 + day.exercises.count * 18)
                if y + estimatedHeight > pageHeight - margin - 30 {
                    drawFooter(in: context.cgContext, margin: margin, pageWidth: pageWidth, pageHeight: pageHeight)
                    context.beginPage()
                    y = margin
                }
                y = drawDaySection(in: context.cgContext, at: y, margin: margin, contentWidth: contentWidth, day: day, dayNumber: index + 1)
            }

            drawFooter(in: context.cgContext, margin: margin, pageWidth: pageWidth, pageHeight: pageHeight)
        }
    }

    static func savePDFToTemp(data: Data, goalName: String) -> URL? {
        let sanitized = goalName.isEmpty ? "PT_Plan" : goalName.replacingOccurrences(of: " ", with: "_")
        let dateStr = fileDateFormatter.string(from: .now)
        let fileName = "PT_Plan_\(sanitized)_\(dateStr).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        do {
            try data.write(to: url)
            return url
        } catch {
            return nil
        }
    }

    private static func drawHeader(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat, plan: WeeklyPlan, goal: PTGoal?) -> CGFloat {
        var currentY = y

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 16),
            .foregroundColor: UIColor.black
        ]
        let title = "PT TRAINING PLAN"
        let titleSize = (title as NSString).size(withAttributes: titleAttrs)
        let titleX = (pageWidth - titleSize.width) / 2
        (title as NSString).draw(at: CGPoint(x: titleX, y: currentY), withAttributes: titleAttrs)
        currentY += titleSize.height + 4

        let subtitleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.darkGray
        ]
        let subtitle = "Generated by MVM Army"
        let subtitleSize = (subtitle as NSString).size(withAttributes: subtitleAttrs)
        let subtitleX = (pageWidth - subtitleSize.width) / 2
        (subtitle as NSString).draw(at: CGPoint(x: subtitleX, y: currentY), withAttributes: subtitleAttrs)
        currentY += subtitleSize.height + 12

        return currentY
    }

    private static func drawPlanSummary(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, plan: WeeklyPlan, goal: PTGoal?) -> CGFloat {
        var currentY = y

        let headerRect = CGRect(x: margin, y: currentY, width: contentWidth, height: 22)
        ctx.setFillColor(UIColor(white: 0.15, alpha: 1).cgColor)
        ctx.fill(headerRect)

        let headerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 9),
            .foregroundColor: UIColor.white
        ]
        ("PLAN OVERVIEW" as NSString).draw(at: CGPoint(x: margin + 8, y: currentY + 6), withAttributes: headerAttrs)
        currentY += 22 + 6

        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 8),
            .foregroundColor: UIColor.darkGray
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.black
        ]

        let thirdWidth = (contentWidth - 16) / 3

        let goalText = goal?.rawValue ?? (plan.ptGoal.isEmpty ? "General" : plan.ptGoal)
        drawField(in: ctx, at: currentY, x: margin, width: thirdWidth, label: "GOAL", value: goalText, labelAttrs: labelAttrs, valueAttrs: valueAttrs)
        drawField(in: ctx, at: currentY, x: margin + thirdWidth + 8, width: thirdWidth, label: "WEEK", value: "\(plan.currentWeek) of \(plan.totalWeeks)", labelAttrs: labelAttrs, valueAttrs: valueAttrs)

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM d, yyyy"
        let dateStr: String
        if let first = plan.days.first, let last = plan.days.last {
            dateStr = "\(dateFormatter.string(from: first.date)) – \(dateFormatter.string(from: last.date))"
        } else {
            dateStr = dateFormatter.string(from: plan.weekStartDate)
        }
        drawField(in: ctx, at: currentY, x: margin + (thirdWidth + 8) * 2, width: thirdWidth, label: "DATES", value: dateStr, labelAttrs: labelAttrs, valueAttrs: valueAttrs)

        currentY += 32 + 8

        let workoutDays = plan.days.filter { !$0.isRestDay }.count
        let restDays = plan.days.filter { $0.isRestDay }.count
        let summaryText = "\(workoutDays) workout days · \(restDays) rest days · \(plan.days.flatMap(\.exercises).count) total exercises"
        let summaryAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 9),
            .foregroundColor: UIColor.gray
        ]
        (summaryText as NSString).draw(at: CGPoint(x: margin, y: currentY), withAttributes: summaryAttrs)
        currentY += 18

        return currentY
    }

    private static func drawDaySection(in ctx: CGContext, at y: CGFloat, margin: CGFloat, contentWidth: CGFloat, day: WorkoutDay, dayNumber: Int) -> CGFloat {
        var currentY = y

        let dayFormatter = DateFormatter()
        dayFormatter.dateFormat = "EEEE, MMM d"

        let dayHeaderRect = CGRect(x: margin, y: currentY, width: contentWidth, height: 20)
        let headerColor = day.isRestDay ?
            UIColor(red: 0.2, green: 0.3, blue: 0.4, alpha: 1.0) :
            UIColor(red: 0.19, green: 0.34, blue: 0.63, alpha: 1.0)
        ctx.setFillColor(headerColor.cgColor)
        ctx.fill(dayHeaderRect)

        let dayHeaderAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 9),
            .foregroundColor: UIColor.white
        ]
        let dayLabel = "DAY \(dayNumber) — \(dayFormatter.string(from: day.date).uppercased())"
        (dayLabel as NSString).draw(at: CGPoint(x: margin + 8, y: currentY + 5), withAttributes: dayHeaderAttrs)

        if !day.tags.isEmpty {
            let tagText = day.tags.prefix(2).joined(separator: " · ")
            let tagAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 8),
                .foregroundColor: UIColor.white.withAlphaComponent(0.7)
            ]
            let tagSize = (tagText as NSString).size(withAttributes: tagAttrs)
            (tagText as NSString).draw(at: CGPoint(x: margin + contentWidth - tagSize.width - 8, y: currentY + 6), withAttributes: tagAttrs)
        }

        currentY += 20 + 2

        if day.isRestDay {
            let restAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.italicSystemFont(ofSize: 10),
                .foregroundColor: UIColor.gray
            ]
            ("Recovery & Mobility — Active rest day" as NSString).draw(at: CGPoint(x: margin + 8, y: currentY + 4), withAttributes: restAttrs)
            currentY += 24
        } else {
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 11),
                .foregroundColor: UIColor.black
            ]
            (day.title as NSString).draw(at: CGPoint(x: margin + 8, y: currentY + 2), withAttributes: titleAttrs)
            currentY += 18

            let nameAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9),
                .foregroundColor: UIColor.black
            ]
            let detailAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 8),
                .foregroundColor: UIColor.darkGray
            ]
            let notesAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.italicSystemFont(ofSize: 7.5),
                .foregroundColor: UIColor.gray
            ]

            for exercise in day.exercises {
                let bullet = "•  \(exercise.name)"
                (bullet as NSString).draw(at: CGPoint(x: margin + 12, y: currentY), withAttributes: nameAttrs)

                let detail = exercise.displayDetail
                let detailSize = (detail as NSString).size(withAttributes: detailAttrs)
                (detail as NSString).draw(at: CGPoint(x: margin + contentWidth - detailSize.width - 8, y: currentY + 1), withAttributes: detailAttrs)

                currentY += 14

                if !exercise.notes.isEmpty {
                    let notesText = "   \(exercise.notes)"
                    (notesText as NSString).draw(at: CGPoint(x: margin + 20, y: currentY), withAttributes: notesAttrs)
                    currentY += 12
                }
            }

            currentY += 4
        }

        ctx.setStrokeColor(UIColor(white: 0.85, alpha: 1).cgColor)
        ctx.setLineWidth(0.3)
        ctx.move(to: CGPoint(x: margin, y: currentY))
        ctx.addLine(to: CGPoint(x: margin + contentWidth, y: currentY))
        ctx.strokePath()
        currentY += 6

        return currentY
    }

    private static func drawField(in ctx: CGContext, at y: CGFloat, x: CGFloat, width: CGFloat, label: String, value: String, labelAttrs: [NSAttributedString.Key: Any], valueAttrs: [NSAttributedString.Key: Any]) {
        let fieldRect = CGRect(x: x, y: y, width: width, height: 32)
        ctx.setStrokeColor(UIColor(white: 0.75, alpha: 1).cgColor)
        ctx.setLineWidth(0.3)
        ctx.stroke(fieldRect)

        (label as NSString).draw(at: CGPoint(x: x + 4, y: y + 2), withAttributes: labelAttrs)
        let displayValue = value.isEmpty ? "—" : value
        (displayValue as NSString).draw(at: CGPoint(x: x + 4, y: y + 15), withAttributes: valueAttrs)
    }

    private static func drawFooter(in ctx: CGContext, margin: CGFloat, pageWidth: CGFloat, pageHeight: CGFloat) {
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 7),
            .foregroundColor: UIColor.gray
        ]
        let footerY = pageHeight - margin + 4
        let dateStr = fileDateFormatter.string(from: .now)

        let leftText = "PT TRAINING PLAN"
        (leftText as NSString).draw(at: CGPoint(x: margin, y: footerY), withAttributes: footerAttrs)

        let rightText = "Generated \(dateStr) — MVM Army"
        let rightSize = (rightText as NSString).size(withAttributes: footerAttrs)
        (rightText as NSString).draw(at: CGPoint(x: pageWidth - margin - rightSize.width, y: footerY), withAttributes: footerAttrs)
    }

    private static let fileDateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyyMMdd"
        return f
    }()
}
